### ISSUE TITLE
undefined reference to `typeinfo for llvm_dsp_factory'

### ISSUE THREAD

**Issue by muziker** [grame-cncm/faustlive#10]
I'm getting this during compilation of faustlive. I'm using llvm 6.0.1 with rtti, QT5. Faust itself is working.

**Comment by sletz** [comment]
Do you have a more precise log ? Thanks.

**Comment by sletz** [comment]
It seems you don"t have **libfaust** compiled and available.  You'll have to use `make all ` at top-level to build the libfaust library. (see also : https://github.com/grame-cncm/faust/wiki)

**Comment by muziker** [comment]
The default target in the faust build directory is all. And it is the same on the initial directory. The output for the build makefile is:
cd faustdir && cmake -DINCLUDE_STATIC=on ..
-- In target faust: include ASMJS backend
-- In target faust: include C backend
-- In target faust: include CPP backend
-- In target faust: include JAVA backend
-- In target faust: include JS backend
-- In target faust: include OCPP backend
-- In target faust: include WASM backend
-- In target staticlib: include ASMJS backend
-- In target staticlib: include C backend
-- In target staticlib: include CPP backend
-- In target staticlib: include JAVA backend
-- In target staticlib: include JS backend
-- In target staticlib: include OCPP backend
-- In target staticlib: include WASM backend
-- In target dynamiclib: include ASMJS backend
-- In target dynamiclib: include C backend
-- In target dynamiclib: include CPP backend
-- In target dynamiclib: include JAVA backend
-- In target dynamiclib: include JS backend
-- In target dynamiclib: include OCPP backend
-- In target dynamiclib: include WASM backend
-- In target wasmlib: include WASM backend
-- In target asmjslib: include ASMJS backend
-- Found libmicrohttpd 0.9.44
-- Install location is /usr/local
-- Include targets: faust;staticlib;dynamiclib osc;http

And has the targets staticlib and dynamiclib. I double checked the existence of libfaust as well. It is there.

**Comment by sletz** [comment]
LLVM backend has to be built also.

**Comment by muziker** [comment]
Compiling the faust project again: The initial directory makefile default is make all. The make all doesn't change the selected backends. So what i did, was replace the regular.cmake with the all.cmake.  If the user compiles the faust project to begin with, the faustdir is the build directory with all the configuration details in the CMakeCache.txt, and this doesn't change even if you replace the backends.txt with the cmake file you want. The README isn't clear that faust/build is one set of config files, and faustdir, is another set of config files. 

After compiling with the llvm backend in, 
cd faustdir && cmake -DINCLUDE_STATIC=on -DINCLUDE_DYNAMIC=on -DINCLUDE_HTTP=on ..
-- Found LLVM 6.0.1
-- In target faust: include ASMJS backend
-- In target faust: include C backend
-- In target faust: include CPP backend
-- In target faust: include FIR backend
-- In target faust: include INTERP backend
-- In target faust: include JAVA backend
-- In target faust: include JS backend
-- In target faust: include OCPP backend
-- In target faust: include RUST backend
-- In target faust: include WASM backend
-- In target faust: include LLVM backend
-- In target staticlib: include ASMJS backend
-- In target staticlib: include C backend
-- In target staticlib: include CPP backend
-- In target staticlib: include FIR backend
-- In target staticlib: include INTERP backend
-- In target staticlib: include JAVA backend
-- In target staticlib: include JS backend
-- In target staticlib: include OCPP backend
-- In target staticlib: include RUST backend
-- In target staticlib: include WASM backend
-- In target staticlib: include LLVM backend
-- In target dynamiclib: include ASMJS backend
-- In target dynamiclib: include C backend
-- In target dynamiclib: include CPP backend
-- In target dynamiclib: include FIR backend
-- In target dynamiclib: include INTERP backend
-- In target dynamiclib: include JAVA backend
-- In target dynamiclib: include JS backend
-- In target dynamiclib: include OCPP backend
-- In target dynamiclib: include RUST backend
-- In target dynamiclib: include WASM backend
-- In target dynamiclib: include LLVM backend
-- In target wasmlib: include WASM backend
-- In target asmjslib: include ASMJS backend
-- Found libmicrohttpd 0.9.44
-- Install location is /usr/local
-- Include targets: faust;staticlib;dynamiclib osc;http

I'm still getting the typeinfo error. Should i be using a different version of the llvm?

**Comment by muziker** [comment]
Looking through the symbols in libfaust.so,  the various llvm_dsp_factory are there:
 31122: 000000000081c710    21 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 31549: 000000000081e9f0   218 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 32054: 0000000000822f60    23 FUNC    WEAK   DEFAULT   12 _ZN20llvm_dsp_factory_aux
 32166: 000000000081c9f0  3617 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 32646: 0000000000822f00    34 FUNC    WEAK   DEFAULT   12 _ZN16llvm_dsp_factory16ge
 33575: 0000000000823150   242 FUNC    WEAK   DEFAULT   12 _ZN16llvm_dsp_factory10ge
 34097: 000000000081ad70   342 FUNC    GLOBAL DEFAULT   12 _ZN16llvm_dsp_factory17cr
 34296: 000000000081e420     6 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 35003: 00000000029a9ec0    56 OBJECT  GLOBAL DEFAULT   27 _ZN20llvm_dsp_factory_aux
 35146: 00000000029a9ef8     4 OBJECT  GLOBAL DEFAULT   27 _ZN20llvm_dsp_factory_aux
 36669: 000000000081f070   861 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 38350: 00000000029a9ea0     8 OBJECT  GLOBAL DEFAULT   27 _ZN20llvm_dsp_factory_aux
 38425: 000000000081a8e0    74 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 39819: 0000000000822c00   279 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 41284: 000000000081c4b0   548 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 42468: 000000000081c730   394 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux
 42857: 0000000000823510   124 FUNC    WEAK   DEFAULT   12 _ZN16llvm_dsp_factoryD2Ev
 43152: 000000000081c6e0    36 FUNC    GLOBAL DEFAULT   12 _ZN20llvm_dsp_factory_aux

**Comment by sletz** [comment]
Is is brew LLVM? Or MacPorts?

**Comment by muziker** [comment]
It is from the github. version 6.0.1. Maybe it is something in the makefile? I do have projucer installed.

**Comment by sletz** [comment]
Can you possibly try with LLVM Macport or brew version ?

**Comment by muziker** [comment]
I'm on linux though.

**Comment by muziker** [comment]
readelf -sW libfaust.so.2.5.34 |c++filt |grep typeinfo  |  grep dsp_factory  | grep llvm

I tried running this, and it did not show any information

**Comment by sletz** [comment]
@dfober : any idea here?

**Comment by dfober** [comment]
Do you mean you compiled llvm from the git repository ?
Could you send the output of 'llvm-config --version' , 'llvm-config --libs' and  'llvm-config --has-rtti'?

**Comment by muziker** [comment]
I compiled llvm with rtti yes, though supposedly, according to many online docs, from llvm 5, it doesn't need to be either rtti or no-rtti anymore.

llvm-config --has-rtti
YES
llvm-config --version
6.0.1
llvm-config --libs
-lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMMIRParser -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMCoverage -lLLVMTableGen -lLLVMDlltoolDriver -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiAsmPrinter -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMARMUtils -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMWindowsManifest -lLLVMFuzzMutate -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle

**Comment by dfober** [comment]
I've tried on Unbuntu 16.04 using the pre-build binaries (http://releases.llvm.org/download.html#6.0.0): 
it compiles and  it works. Could you try on your side?

**Comment by muziker** [comment]
I've added the llvm binaries, and used update-alternatives to switch the llvm-config. llvm-config --has-rtti is no. Unfortunately, it is the same thing.

**Comment by muziker** [comment]
Does QT need special compilation flags?

**Comment by muziker** [comment]
Ok so managed to solve this, but haven't tried out all the functionalities. The problem is a mixture of no-rtti and rtti. From llvm chatter on the web, the use of the latest llvm would solve the rtti vs no-rtti, but well that isn't the case, or rather the answers are ambiguous as to if that works with mixing rtti and no-rtti code. So in the faust/build/faustdir, which is the secondary build directory of faust, replace all occurrences of -fno-rtti with -frtti. The cmakelists.txt file in the faust/build directory has some property statements that appends this string.
I might be making a mistake with the assumption that -frtti is fine in all environments, so any clarity would be helpful.
In any case, faustlive builds once faust is recompiled with -frtti, which is not mentioned in the faust installation/readme documentation except in the line that says llvm needs rtti.
