### ISSUE TITLE
Which faust2 to compile on linux in 2018?

### ISSUE THREAD

**Issue by alikthename** [grame-cncm/faustlive#15]
Readme file in "linux" directory says that FaustLive depends on faust2 branch of faust from sourceforge
But Readme in faust2 branch from sourceforge states:
"The project has been moved to GitHub (https://github.com/grame-cncm/faust). Do not use this repository anymore !"
Now  in https://github.com/grame-cncm/faust there is no faust2 branch. There is "old-faust2", is that the one I should compile in order to have fully local FaustLive installation?

**Comment by sletz** [comment]
1) the reader is obsolete, juste use the Faust master-de branch. For  faustLive to sure to use the `dev` branch if you want latest developments.

2)  we are in the process to recompile FaustLive on all platforms (OS X, Windows, Linux), in order to make a new binary release soon.
