### ISSUE TITLE
No rule to make target '../../Resources/styles.qrc.in'

### ISSUE THREAD

**Issue by alikthename** [grame-cncm/faustlive#16]
I have compiled faust from master-dev branch with "most" target.
Now when I try to compile dev branch from faustlive I get following:

make all
if test -d .git; then git submodule update --init; fi
Submodule 'Resources/Libs' (https://github.com/grame-cncm/faustlibraries.git) registered for path 'Resources/Libs'
Cloning into '/mnt/3/src/faust2_2018/faustlive/Resources/Libs'...
Submodule path 'Resources/Libs': checked out '552b78c6502192b6fbc93ceeaa05c8b1093530f2'
make -C Build/Linux
make[1]: Entering directory '/mnt/3/src/faust2_2018/faustlive/Build/Linux'
make[1]: *** No rule to make target '../../Resources/styles.qrc.in', needed by '../../Resources/styles.qrc'.  Stop.
make[1]: Leaving directory '/mnt/3/src/faust2_2018/faustlive/Build/Linux'
Makefile:17: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dfober** [comment]
The build process has been revised but it's still a work in progress. You can try:
~~~~
make -C Build
~~~~
if it doesn't work, use direct `qmake`commands from a separate folder e.g.
~~~~
mkdir -p Build/fldir
cd Build/fldir
qmake ..
make
~~~~
Note that you should use the `dev` branch.

**Comment by scalarwaves** [comment]
This trick worked for me, thanks!

**Comment by sletz** [comment]
Probably solved now. Reopen if needed.
