### ISSUE TITLE
error: ‘class JA_audioFader’ has no member named ‘setShutdownCb’

### ISSUE THREAD

**Issue by alowell-ssl** [grame-cncm/faustlive#17]
Ubuntu 18.04, running make I get:

../../src/Audio/JA/JA_audioManager.cpp:26:20: error: ‘class JA_audioFader’ has no member named ‘setShutdownCb’; did you mean ‘shutdown’?
     fCurrentAudio->setShutdownCb(cb, arg);
                    ^~~~~~~~~~~~~
                    shutdown

**Comment by yurivict** [comment]
I also get this, and with the latest version of faust: 2.14.4

**Comment by yurivict** [comment]
@sletz IMO, you should re-release both projects, because all systems who package ```faust``` and ```faustlive``` will have the same problems, and they are supposed to come here and find that taking the latest tags fix the problems. If the release is broken, it should be released again (with the next version number).
