### ISSUE TITLE
crashes on startup, the first launch (on El Capitan but not on Sierra)

### ISSUE THREAD

**Issue by an2netto** [grame-cncm/faustlive#18]
Report:

Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /Applications/FaustLive.app/Contents/MacOS/../Frameworks/libmicrohttpd.12.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by sletz** [comment]
FL does not work on El Capitan anymore.
