### ISSUE TITLE
Build fails: No rule to make target '../Resources/Libs/signals.lib'

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faustlive#19]
The error message:
```
gmake[2]: *** No rule to make target '../Resources/Libs/signals.lib', needed by 'tmp/qrc_application.cpp'.  Stop.
```

```faust-2.14.4``` on FreeBSD 11.2

**Comment by yurivict** [comment]
@dfober  The 2.5.0 release is broken, up to and including the latest commit 7264508, the error message is above.

Could you please make releases of both projects that build with each other?


Thank you.

**Comment by dfober** [comment]
Compilation is now checked with travis. It works with the dev branch. Could you check again. Master branch should be updated soon (a new release is planned).
