### ISSUE TITLE
ALSA lib is linked despite its option not being chosen

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faustlive#3]
Currently there are only variables for JACK and PORTAUDIO.

Also, setting JACK=0 (```make JACK=0```) for some  reason still links with Jack for me.

**Comment by sletz** [comment]
Disable ALSA ? There is no ALSA backend in FL for now. On Linux JACK has to be used.

**Comment by yurivict** [comment]
But it links to alsalib.

**Comment by yurivict** [comment]
It first prints:
```
Project MESSAGE: ALSA NOT LINKED
```
but the executable ends up linked with ALSA. This is a bug.

Another bug is that Build/{arch}/Makefile looks at the variable JACK, but all it does is setting ```JVAR=1``` which is already ```=1```. JACK variable should be either removed, or made to work.

**Comment by sletz** [comment]
PR welcome !

**Comment by yurivict** [comment]
This is actually a bug. Build says:
> Project MESSAGE: ALSA NOT LINKED
but ```libasound.so``` is still linked.

**Comment by sletz** [comment]
PR welcome !

**Comment by sletz** [comment]
Probably solved now. Reopen if needed.
