### ISSUE TITLE
sources for Resources/FaustLive*.png?

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faustlive#31]
it seems as if  the `Resources/FaustLive*.png` files have been generated from .xmp sources.
Are these original files available somewhere?

(this is part of the Debian-wants-the-preferred-form-of-modification dance again ;-))

**Comment by sletz** [comment]
We don't have the source anymore.

**Comment by umlaeute** [comment]
thanks for confirming.
this is good enough for us
