### ISSUE TITLE
Unable to build against libmicrohttpd-0.9.71 with g++-10

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faustlive#33]
building faustlive fails with libmicrohttpd-0.9.71 with g++-10, because FaustLive returns `int` where really a `MHD_Result` is expected.
`MHD_Result` is a simple enum encapsulating a boolean value (`MHD_NO = 0,  MHD_YES = 1`), but in C++-land enums are not implicitely converted to `int` and vice-versa, so the build fails.

i haven't actually checked whether the problem originates from an updated `libmicrohttpd` (having switched from int to enum) or a stricter `g++-10`.

you can get a patch that fixes the problem from https://salsa.debian.org/multimedia-team/faustlive/-/blob/master/debian/patches/microhttpd.patch

**Comment by sletz** [comment]
This change https://github.com/grame-cncm/faustlive/commit/c16565dc1b616ac0aad7c303c1997fa9e57177ab should be better, since it makes the code compile with older and newer (0.9.71) version of libmicrohttpd.

**Comment by umlaeute** [comment]
cool thanks
