### ISSUE TITLE
Not working in Pipewire

### ISSUE THREAD

**Issue by jpcima** [grame-cncm/faustlive#40]
On loading a dsp file, there is this error `Impossible to init JackAudio Client`.

This error happens from `faust/audio/jack_dsp.h` in `jack_client_open`.
It's hard to tell why this error occurs in FaustLive only, because the very same call works in a minimal C program.

FaustLive revision 095671c
Pipewire 0.3.28

**Comment by sletz** [comment]
I understand Pipewire  is supposed to emulate JACK API right? So try to undersatnd first if Pipewire is the problem.

**Comment by jpcima** [comment]
It's correct, pipewire emulates jack API.
It does so by providing a substitute libjack.

It's like this
```
> ls -l /usr/lib/pipewire-0.3/jack                                                                            ~ 
lrwxrwxrwx   12 root 19 mai   14:37 libjack.so -> libjack.so.0*
lrwxrwxrwx   18 root 19 mai   14:37 libjack.so.0 -> libjack.so.0.328.0*
.rwxr-xr-x 182k root 19 mai   14:37 libjack.so.0.328.0*
lrwxrwxrwx   15 root 19 mai   14:37 libjacknet.so -> libjacknet.so.0*
lrwxrwxrwx   21 root 19 mai   14:37 libjacknet.so.0 -> libjacknet.so.0.328.0*
.rwxr-xr-x  14k root 19 mai   14:37 libjacknet.so.0.328.0*
lrwxrwxrwx   18 root 19 mai   14:37 libjackserver.so -> libjackserver.so.0*
lrwxrwxrwx   24 root 19 mai   14:37 libjackserver.so.0 -> libjackserver.so.0.328.0*
.rwxr-xr-x 194k root 19 mai   14:37 libjackserver.so.0.328.0*
```

```
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/ld.so.conf.d/pipewire-jack.conf
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ /usr/lib/pipewire-0.3/jack
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by sletz** [comment]
So I suggest debugging the JACK API calls in FL to understand where and why it fails.

**Comment by jpcima** [comment]
It's as noted in the OP, the failure is at `jack_client_open` in faust system headers.
It returns a null for the client.

If I'm running the very same function call in a self-made program, it works.
It suggests something wrong happening in FaustLive at another place, which I don't know how well to identify.

Also I'm at trouble debugging it, because it seems having incompatibility with various debug tools.

```
#include <jack/jack.h>
#include <stdio.h>

int main()
{
    jack_status_t status = {};
    jack_client_t *client = jack_client_open("FLW-1", JackNullOption, &status);

    if (!client) {
        fprintf(stderr, "Status %d\n", status);
        return 1;
    }

    fprintf(stderr, "Success\n");
    return 0;
}
```

**Comment by sletz** [comment]
Well do you suggest me to fix FL that do not work anymore with PW that does not emulate JACK API the way **it was working** before PW even appear !? I suggest the other way for now, until you can prove FL code is wrong somewhere.

**Comment by magnetophon** [comment]
FWIW: On NixOS it works for me.
pipewire-0.3.49
faustlive-2.5.8

**Comment by jpcima** [comment]
It works now for me as well.

**Comment by sletz** [comment]
Great !, I guess somewhat has been fixed at pipewire level since nothing has been changed in FL code...
