### ISSUE TITLE
Can't see FaustLive as a midi source or destination in coreaudio

### ISSUE THREAD

**Issue by joshielevy** [grame-cncm/faustlive#41]
FaustLive 2.5.6
MacOS 11.4
Macbook pro M1

When I enable MIDI and hit apply, I don't see FaustLive as a midi source or destination in coreaudio (for example in MidiFire). I've tried adding the -midi flag in the compilation options box but it doesn't do anything.

Any suggestions?

**Comment by sletz** [comment]
FaustLive scans all CoreMidi ports to get vent from them, you can possibly use IAC busses also.

**Comment by joshielevy** [comment]
Hmmm...the miditester example isn't working...do you have a simple .dsp example that should respond to note on/note off events?

**Comment by joshielevy** [comment]
Actually forget it - I figured it out - got a note to play via the midi controller in faustlive. Thanks anyway!
