### ISSUE TITLE
fi.svf not working (issue with environments?)

### ISSUE THREAD

**Issue by jmckernon** [grame-cncm/faustlive#43]
The following code will compile in faust itself but yields an error in FaustLive:

```
import("stdfaust.lib");
process = no.noise : fi.svf.bp(1000,1);
```

Is it something to do with the fact that svf is an environment within fi? The error message is:

```
svf : 108 : ERROR : undefined symbol : svf
```

Using FaustLive version 2.30.9.

**Comment by sletz** [comment]
Tested and working with latest https://github.com/grame-cncm/faustlive/releases/tag/2.5.6

**Comment by jmckernon** [comment]
Ah, thanks Stéphane. I tried to check out the latest version to test with but I had problems compiling from the source, so I thought I would at least submit the issue in the meantime.

If it's still an issue when I manage to test on the latest version, then I may reopen this, but for now I'll close the issue. Thanks.

**Comment by sletz** [comment]
Possibly try to compile from the GitHub repo.

**Comment by jmckernon** [comment]
Actually, I'll reopen this. After installing faust 2.34.6, I could update FaustLive to version 2.5.6, and I found that I still have the same issue in that version.

**Comment by sletz** [comment]
Try to remove the cache folder` .FaustLive-CurrentSession-2.0` (hidden with '.' on macOS).

**Comment by jmckernon** [comment]
Yep, it looks like that fixed it. Many thanks.

**Comment by sletz** [comment]
Should be improved the next release with this https://github.com/grame-cncm/faustlive/commit/d39b7f14533f4d83a28757d1a1afc6224f0dd443.
