### ISSUE TITLE
ALSA audio not supported

### ISSUE THREAD

**Issue by jazamatronic** [grame-cncm/faustlive#50]
Hello,

I tried to build with ALSA support on Linux and get the following:

```
/data/FaustLive-2.5.12/src/Audio/AudioCreator.cpp:38:14: fatal error: AL_audioFactory.h: Aucun fichier ou dossier de ce type
   38 |     #include "AL_audioFactory.h"
      |              ^~~~~~~~~~~~~~~~~~~
```
I can see the corresponding JACK files under src/audio/JA, but there is no equivalent src/audio/AL

Cheers

**Comment by sletz** [comment]
There is no ALSA support for now.
