### ISSUE TITLE
compilation@debian9 fails

### ISSUE THREAD

**Issue by michal-cab** [grame-cncm/faustlive#6]
hello,
have an problems with compiling faustlive under debian 9. i have llvm3.9. and libjack-dev (dep jackd1) and other deps installed. i compiled faust Version 2.5.9 without any problems. when i do make in Build/Linux it spills:

In file included from /usr/local/include/faust/audio/jack-dsp.h:40:0,
                 from ../../src/Audio/JA/JA_audioFader.h:16,
                 from ../../src/Audio/JA/JA_audioManager.cpp:13:
/usr/local/include/faust/midi/jack-midi.h: In member function ‘void jack_midi_handler::processMidiOutBuffer(void*, bool)’:
/usr/local/include/faust/midi/jack-midi.h:85:52: error: ‘jack_midi_reset_buffer’ was not declared in this scope
                 jack_midi_reset_buffer(port_buf_out);
                                                    ^
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual bool JA_audioManager::initAudio(QString&, const char*, bool)’:
../../src/Audio/JA/JA_audioManager.cpp:37:42: error: no matching function for call to ‘JA_audioFader::init(const char*&, int, bool&)’
     if (fCurrentAudio->init(name, 0, midi)) {
                                          ^
In file included from ../../src/Audio/JA/JA_audioFader.h:16:0,
                 from ../../src/Audio/JA/JA_audioManager.cpp:13:
/usr/local/include/faust/audio/jack-dsp.h:562:22: note: candidate: virtual bool jackaudio_midi::init(const char*, dsp*)
         virtual bool init(const char* name, dsp* dsp)
                      ^~~~
/usr/local/include/faust/audio/jack-dsp.h:562:22: note:   candidate expects 2 arguments, 3 provided
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual bool JA_audioManager::setDSP(QString&, dsp*, const char*)’:
../../src/Audio/JA/JA_audioManager.cpp:45:39: warning: unused parameter ‘error’ [-Wunused-parameter]
 bool JA_audioManager::setDSP(QString& error, dsp* DSP, const char* port_name)
                                       ^~~~~
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual void JA_audioManager::connect_Audio(std::__cxx11::string)’:
../../src/Audio/JA/JA_audioManager.cpp:95:28: error: ‘class JA_audioFader’ has no member named ‘default_connections’; did you mean ‘defaultConnections’?
             fCurrentAudio->default_connections();
                            ^~~~~~~~~~~~~~~~~~~
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual int JA_audioManager::get_buffer_size()’:
../../src/Audio/JA/JA_audioManager.cpp:114:27: error: ‘class JA_audioFader’ has no member named ‘get_buffer_size’; did you mean ‘getBufferSize’?
     return fCurrentAudio->get_buffer_size();
                           ^~~~~~~~~~~~~~~
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual int JA_audioManager::get_sample_rate()’:
../../src/Audio/JA/JA_audioManager.cpp:119:27: error: ‘class JA_audioFader’ has no member named ‘get_sample_rate’; did you mean ‘getSampleRate’?
     return fCurrentAudio->get_sample_rate();
                           ^~~~~~~~~~~~~~~
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual bool JA_audioManager::initAudio(QString&, const char*, bool)’:
../../src/Audio/JA/JA_audioManager.cpp:43:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile-qt:711: recipe for target '../../src/objectsFolder/JA_audioManager.o' failed
make[1]: *** [../../src/objectsFolder/JA_audioManager.o] Error 1
make[1]: Leaving directory '/home/tao/source/faustlive/Build/Linux'
Makefile:59: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sletz** [comment]
Can you try latest GIT dev branch : https://github.com/grame-cncm/faustlive/tree/dev ?

**Comment by michal-cab** [comment]
thnx for fast re, i tried to download dev branch, and there is less errors but still some problem concerning jack_midi_reset_buffer :-0

now  make spills this:
In file included from /usr/local/include/faust/audio/jack-dsp.h:40:0,
                 from ../../src/Audio/JA/JA_audioFader.h:16,
                 from ../../src/Audio/JA/JA_audioManager.cpp:13:
/usr/local/include/faust/midi/jack-midi.h: In member function ‘void jack_midi_handler::processMidiOutBuffer(void*, bool
’:
/usr/local/include/faust/midi/jack-midi.h:85:52: error: ‘jack_midi_reset_buffer’ was not declared in this scope
                 jack_midi_reset_buffer(port_buf_out);
                                                    ^
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual bool JA_audioManager::initAudio(QString&, const char*, bool)’:
../../src/Audio/JA/JA_audioManager.cpp:35:72: warning: unused parameter ‘midi’ [-Wunused-parameter]
 bool JA_audioManager::initAudio(QString& error, const char* name, bool midi)
                                                                        ^~~~
../../src/Audio/JA/JA_audioManager.cpp: In member function ‘virtual bool JA_audioManager::setDSP(QString&, dsp*, const char*)’:
../../src/Audio/JA/JA_audioManager.cpp:45:39: warning: unused parameter ‘error’ [-Wunused-parameter]
 bool JA_audioManager::setDSP(QString& error, dsp* DSP, const char* port_name)
                                       ^~~~~
Makefile-qt:708: recipe for target '../../src/objectsFolder/JA_audioManager.o' failed
make[1]: *** [../../src/objectsFolder/JA_audioManager.o] Error 1
make[1]: Leaving directory '/home/tao/source/faustlive-dev/Build/Linux'
Makefile:59: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sletz** [comment]
Then you'll have to use a recent JACK version (1.9.11 or latest GIT version) : https://github.com/jackaudio/jack2
