### ISSUE TITLE
Issues when using i3wm (tiling window manager)

### ISSUE THREAD

**Issue by Barabas5532** [grame-cncm/faustlive#60]
I have found a few issues while using FaustLive on Arch Linux with [i3wm](https://i3wm.org/).

## Initial window floats

The initial "WELCOME TO FAUSTLIVE" window is floating by default. It would be better if it was allowed to tile like most other windows and apps. It already scales fine to full screen if I tile it manually.

## Screen layout breaks when expanding the "Parameters" panel

After opening a faust file from the initial window, the window shows the faust project's parameters fine. However after clicking on the "Parameters" button at the top of the window, the drawing is broken. Looks like the window tries to resize itself, but it confict with the size set by the window manager, and drawing only happens in a part of the window:

![image](https://github.com/user-attachments/assets/8b0b3593-4621-4eca-ab2a-52393a1ead6e)

It is still broken closing the Parameters panel:

![image](https://github.com/user-attachments/assets/c2d5f358-c35f-4ca3-993b-e6a74c9d32ef)

It is fixed if I resize the window by hand.

## FaustLive window moves to active workspace when the DSP file is updated

1. Open a faust file in FaustLive on workspace 1
2. Open the faust file in a text editor on workspace 2
3. Change the faust file in the editor
4. FaustLive moves to the workspace containing the text editor. It should stay on the workspace where it was opened. It also steals focus from the editor when it appears.

**Comment by sletz** [comment]
This project is not actively maintained anymore.
