### ISSUE TITLE
Error message at startup

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faustlive#8]
Whenever I launch faustlive (on Linux at least), I see this annoying popup:

![image](https://user-images.githubusercontent.com/2853977/35167265-1af4d700-fd55-11e7-9700-eb36dc79935e.png)

Looks like faustlive is trying to load some bad dsp file there. Can we please get rid of this?

This is using the latest faustlive from the dev branch and the latest faust from master-dev.

BTW, the library submodule in faustlive (at Resources/Libs) is outdated as well, it should be updated to the latest from https://github.com/grame-cncm/faustlibraries.

**Comment by sletz** [comment]
Could it be a dirty .FaustLive-CurrentSession-2.0 folder? Try to remove it.

Resources/Libs has been updated.

**Comment by agraef** [comment]
Well, the update of the library submodule seems to have solved this issue. But now I'm getting the error popup `Fri Jan 19 2018  23:30:45: Unable to read file` instead. (I already got that message previously on subsequent launches, forgot to mention it.) So it seems that faustlive is still trying to load a non-existent file on startup there.

**Comment by sletz** [comment]
Could it be a dirty .FaustLive-CurrentSession-2.0 folder? Try to remove it.

**Comment by agraef** [comment]
No, I already tried that (see above).

**Comment by sletz** [comment]
No idea then ))-:

**Comment by agraef** [comment]
Well, if you can't reproduce it then it's more likely a local (read PEBKAC) or maybe a Linux-specific issue. I'll check it out on my MacBook when I update the MacPorts packages.

**Comment by agraef** [comment]
Just built the latest (faust +) faust-live on the Mac and I do *not* get the message there, so my bet is on a Linux-specific issue (if it was some local configuration thing then removing .FaustLive-CurrentSession-2.0 should have solved it, I guess).

Still no idea on how to debug this, though. Bipartitioning on commits will not be very useful here because of the comprehensive changes in Faust. :(

**Comment by sletz** [comment]
There was actually a bug, should be fixed in https://github.com/grame-cncm/faustlive/commit/0031a94bd66a1afe3ac36fa3435b9868c21c8ec6.

**Comment by agraef** [comment]
Works like a charm now, many thanks!
